name: crypto_coins_list
description: Cool crypto application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6

  # Network
  dio: ^5.0.2

  # DI
  get_it: ^7.2.0

  # State management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

  # Date & Localization
  intl: ^0.18.0

  # Logger
  talker_flutter: ^2.4.3
  talker_dio_logger: ^1.3.0
  talker_bloc_logger: ^1.1.0

  # JSON / Storage
  json_annotation: ^4.8.0
  hive_flutter: ^1.1.0

  # Navigation
  auto_route: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0
  auto_route_generator: ^6.1.0
  build_runner: ^2.3.3
  group_button: ^5.3.2 

flutter:
  uses-material-design: true

  assets:
    - assets/svg/